// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rankings.EntityFramework;

namespace Rankings.EntityFramework.Migrations
{
    [DbContext(typeof(RankingsContext))]
    [Migration("20190921215348_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Rankings.EntityFramework.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int?>("RankingId");

                    b.Property<int>("Rating");

                    b.Property<string>("Title");

                    b.HasKey("ItemId");

                    b.HasIndex("RankingId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Rankings.EntityFramework.Entities.Ranking", b =>
                {
                    b.Property<int>("RankingId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("RankingId");

                    b.ToTable("Rankings");
                });

            modelBuilder.Entity("Rankings.EntityFramework.Entities.Item", b =>
                {
                    b.HasOne("Rankings.EntityFramework.Entities.Ranking", "Ranking")
                        .WithMany("Items")
                        .HasForeignKey("RankingId");
                });
#pragma warning restore 612, 618
        }
    }
}
